apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-node
  labels:
    app: example-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-node
      team: devops
  template:
    metadata:
      labels:
        app: example-node
    spec:
      containers:
        - name: example-node
          image: lucasbrito3001/example-test-node:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: example-node-lb
spec:
  type: LoadBalancer
  selector:
    app: example-node
    team: devops
  ports:
    - port: 80
      targetPort: 3000
